/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import elementos.Cliente;
import java.util.ArrayList;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import modelos.ListaCliente;


/**
 *
 * @author joaop
 */
public class fmClientes extends javax.swing.JInternalFrame {
    
    ListaCliente cv;
    
    public fmClientes(ListaCliente cv){
        this.cv = cv;
        this.setBorder(null);
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        initComponents();
        double valorTotal = 0;
        ArrayList<Cliente> clientes = cv.retornarTodos();
        for (int i=0; i< clientes.size(); i++) {
           texto.setText(texto.getText() + "Nome:                       " +
                   clientes.get(i).getNome() + "\n");
           texto.setText(texto.getText() + "Sexo:                       " +
                   clientes.get(i).getSexo() + "\n");
           texto.setText(texto.getText() + "CPF:                        " +
                   clientes.get(i).getCPF() + "\n");
           texto.setText(texto.getText() + "Data de nascimento:         " +
                   clientes.get(i).getNascimento() + "\n\nPassagem:\n");
           texto.setText(texto.getText() + "" + clientes.get(i).getClasse() +
                   "\n");
           texto.setText(texto.getText() + "Valor: R$ " + 
                   clientes.get(i).getValor() + "\n");
           texto.setText(texto.getText() + "Horário:                    " +
                   clientes.get(i).getHorario() + "\n");
           texto.setText(texto.getText() + "Data:                       " +
                   clientes.get(i).getData() + "\n");
           texto.setText(texto.getText() + "De:  " + 
                   clientes.get(i).getCidade());
           texto.setText(texto.getText() + "   Para:  " +
                   clientes.get(i).getDestino() + "\n");
           texto.setText(texto.getText() + "\n---------------------------------"
                   + "------------------------------------------\n");
           valorTotal += clientes.get(i).getValor();
        }
        jLabel3.setText("R$ " + valorTotal);
    }
    /**
     * Creates new form fmClientes
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblX = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(71,71,71));
        jPanel1.setForeground(new java.awt.Color(71, 71, 71));
        jPanel1.setPreferredSize(new java.awt.Dimension(633, 741));

        lblX.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        lblX.setForeground(new java.awt.Color(255, 0, 0));
        lblX.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblX.setText("X ");
        lblX.setToolTipText("");
        lblX.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXMouseClicked(evt);
            }
        });

        texto.setEditable(false);
        texto.setBackground(new java.awt.Color(71, 71, 71));
        texto.setColumns(20);
        texto.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 255, 255));
        texto.setRows(5);
        jScrollPane1.setViewportView(texto);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Clientes:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Valor total:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("                   ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(60, 60, 60)
                .addComponent(lblX, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblX)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblXMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblX;
    private javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables
}
